
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ctrlmesh-mutating
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ctrlmesh-webhook-service
      namespace: {{ .Values.namespace }}
      path: /mutate-namespace
      port: 443
  failurePolicy: Ignore
  name: namesapace.ctrlmesh.mutating.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - namespaces
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ctrlmesh-webhook-service
      namespace: {{ .Values.namespace }}
      path: /mutate-pod
      port: 443
  failurePolicy: Ignore
  name: pod.ctrlmesh.mutating.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: ctrlmesh-webhook-service
      namespace: {{ .Values.namespace }}
      path: /mutate-resource
      port: 443
  failurePolicy: Ignore
  name: resource.ctrlmesh.mutating.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - services
    - statefulsets
    - controllerrevisions
    - configmaps
    - persistentvolumeclaims
    - endpoints
  sideEffects: None
