apiVersion: v1
data:
  resource-config: |
    {{- toYaml .Values.shardingGroupVersionKinds | nindent 4 }}
kind: ConfigMap
metadata:
  name: ctrlmesh-sharding-resource
  namespace: {{ .Values.namespace }}