apiVersion: v1
kind: Service
metadata:
  name: karpor-server
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.port }}
  selector:
    app: karpor-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karpor-server
  name: karpor-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karpor-server
  template:
    metadata:
      labels:
        app: karpor-server
    spec:
      containers:
        - args:
            - --search-storage-type=elasticsearch
            - --elastic-search-addresses=http://elasticsearch.karpor.svc:9200
            - --etcd-servers=http://etcd.karpor.svc:2379
            - --secure-port={{ .Values.port }}
            - --client-ca-file=/etc/karpor/ca.crt
          command:
            - /karpor
          image: kusionstack/karpor:{{ .Values.tag }}
          name: karpor-server
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - mountPath: /etc/karpor/
              name: karpor-secret
      volumes:
        - name: karpor-secret
          secret:
            defaultMode: 420
            secretName: karpor-secret
