apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.elasticsearch.port }}
  selector:
    {{- include "karpor.selectorLabels" (dict "context" . "component" .Values.elasticsearch.name) | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "karpor.labels" (dict "context" . "component" .Values.elasticsearch.name) | nindent 4 }}
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "karpor.selectorLabels" (dict "context" . "component" .Values.elasticsearch.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "karpor.selectorLabels" (dict "context" . "component" .Values.elasticsearch.name) | nindent 8 }}
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: xpack.security.transport.ssl.enabled
              value: "false"
            - name: KIBANA_PASSWORD
              value: dangerous0
            - name: ELASTIC_PASSWORD
              value: elastic
            - name: ES_JAVA_OPTS
              value: -Xms1g -Xmx1g
          image: {{ include "karpor.realImage" (dict "context" . "repo" .Values.elasticsearch.image.repo "tag" .Values.elasticsearch.image.tag) }}
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy }} 
          name: elasticsearch
          ports:
            - containerPort: {{ .Values.elasticsearch.port }}
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
              ephemeral-storage: 10Gi
            requests:
              cpu: "2"
              memory: 4Gi
              ephemeral-storage: 10Gi
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      volumes:
        - emptyDir: {}
          name: data
